name: "Working or Not ?"
run-name: "Working or Not ?"

on:
  workflow_dispatch:
    inputs:
      myVar:
        description: My Variable
        required: false
        default: My variable is not defined (from caller)
        type: string
jobs:
  Call-Another-Workflow:
    uses: 44kia244/test-reusable-workflow/.github/workflows/run.yml@main
    with:
      myVar: ${{ inputs.myVar }}
